ALEXS_MACBOOK_FUNCX_ENDPOINT="674446c2-4dc6-41a6-b767-bf6ce67df702"
ALEXS_MACBOOK_GLOBUS_ENDPOINT="5e02fe02-ad3f-11ec-bf90-ab28bf5d96bb"
# Test send and recv paths on local macbook
ALEXS_MACBOOK_SEND_GLOBUS_REL_PATH="GlobusEndpoint/transfer-flow-test-send"
ALEXS_MACBOOK_SEND_GLOBUS_ABS_PATH="/Users/abrace/GlobusEndpoint/transfer-flow-test-send"
ALEXS_MACBOOK_RECV_GLOBUS_REL_PATH="GlobusEndpoint/transfer-flow-test-recv"
ALEXS_MACBOOK_RECV_GLOBUS_ABS_PATH="/Users/abrace/GlobusEndpoint/transfer-flow-test-recv"
# Search index
ALEXS_TEST_SEARCH_INDEX="6077d057-989d-41e2-b60b-91fe001f0687"

LAMBDA9_GLOBUS_ENDPOINT="a61769ee-130f-11ee-be48-195c41bc0be4"
EAGLE_GLOBUS_ENDPOINT="05d2c76a-e867-4f67-aa57-76edeb0beda0"
EAGLE_SECURE_BIOSYSTEMS_GLOBUS_ENDPOINT="50b5f940-b47e-476b-91f0-237ba762827f"

export LOCAL_FUNCX_ENDPOINT=${ALEXS_MACBOOK_FUNCX_ENDPOINT}
export LOCAL_GLOBUS_ENDPOINT=${ALEXS_MACBOOK_GLOBUS_ENDPOINT}
export LOCAL_GLOBUS_REL_PATH=${ALEXS_MACBOOK_SEND_GLOBUS_REL_PATH}
export LOCAL_GLOBUS_ABS_PATH=${ALEXS_MACBOOK_SEND_GLOBUS_ABS_PATH}

export REMOTE_FUNCX_ENDPOINT=${ALEXS_MACBOOK_FUNCX_ENDPOINT}
export REMOTE_GLOBUS_ENDPOINT=${ALEXS_MACBOOK_GLOBUS_ENDPOINT}
export REMOTE_GLOBUS_REL_PATH=${ALEXS_MACBOOK_RECV_GLOBUS_REL_PATH}
export REMOTE_GLOBUS_ABS_PATH=${ALEXS_MACBOOK_RECV_GLOBUS_ABS_PATH}

export GLOBUS_SEARCH_INDEX=${ALEXS_TEST_SEARCH_INDEX}
