# This test transfers files from one directory in AlexsMacBook Globus
# endpoint (transfer-flow-test-send) to a directory on the Eagle@ALCF
# file system (globus-transfer) to test the ALCF Globus Compute endpoint.

# On AlexsMacBook
local_globus_endpoint: 
  endpoint_id: 5e02fe02-ad3f-11ec-bf90-ab28bf5d96bb
  rel_path: GlobusEndpoint/transfer-flow-test-send
  abs_path: /Users/abrace/GlobusEndpoint/transfer-flow-test-send

# On Eagle@ALCF
remote_globus_endpoint: 
  endpoint_id: 300ef593-e55e-4bc1-ab21-6d26d82c3b99
  rel_path: PicoProbeTestEndpoint/08-18-test
  abs_path: /lus/eagle/projects/APSDataAnalysis/PICOPROBE/PicoProbeTestEndpoint/08-18-test

# This funcX endpoint is on Polaris@ALCF
remote_funcx_endpoint: f53c4fe3-1293-4baa-bdb0-118fab4e56ef
remote_funcx_endpoint_non_compute: f53c4fe3-1293-4baa-bdb0-118fab4e56ef

# picoprobe_testing search index
globus_search_index: 06625170-a9ee-4d68-b8dc-2480c9407966
