# This test transfers files from one directory in AlexsHomeWindows Globus
# endpoint (transfer-flow-test-send) to another directory in AlexsMacBook
# endpoint (transfer-flow-test-recv) to test flows starting on windows.

# On AlexsHomeWindows
local_globus_endpoint: 
  endpoint_id: 4f5d2f40-365e-11ee-9206-5b20905a64b1
  rel_path: transfer-flow-test-send
  abs_path: C:\Users\sprou\.GlobusEndpoint\transfer-flow-test-send

# On AlexsMacBook
remote_globus_endpoint: 
  endpoint_id: 5e02fe02-ad3f-11ec-bf90-ab28bf5d96bb
  rel_path: GlobusEndpoint/transfer-flow-test-recv
  abs_path: /Users/abrace/GlobusEndpoint/transfer-flow-test-recv

# This funcX endpoint is on AlexsMacBook
remote_funcx_endpoint: 674446c2-4dc6-41a6-b767-bf6ce67df702
globus_search_index: 6077d057-989d-41e2-b60b-91fe001f0687
