# This test transfers files from one directory in PicoProbeUserDAComputerGlobus
# endpoint (transfers) to a directory on the Eagle@ALCF file system (globus-transfer) 
# to test the ALCF PicoProbe connection

# On PicoProbeUserDAComputerGlobus
local_globus_endpoint: 
  endpoint_id: 387aaf6e-3302-11ee-9200-5b20905a64b1
  rel_path: MicroscopeData\Brace\transfers
  abs_path: C:\Users\PicoProbeUser\Documents\MicroscopeData\Brace\transfers


# On Eagle@ALCF
remote_globus_endpoint: 
  endpoint_id: 300ef593-e55e-4bc1-ab21-6d26d82c3b99
  rel_path: PicoProbeTestEndpoint/08-21-PicoProbeUser-hyperspectral-prod-v5
  abs_path: /lus/eagle/projects/APSDataAnalysis/PICOPROBE/PicoProbeTestEndpoint/08-21-PicoProbeUser-hyperspectral-prod-v5

# This funcX endpoint is on Polaris@ALCF
remote_funcx_endpoint: d8e16504-eaab-44b6-aa56-ff7d1b6040a3
remote_funcx_endpoint_non_compute: f53c4fe3-1293-4baa-bdb0-118fab4e56ef

# picoprobe_hyperspectral_prod search index
globus_search_index: 5e2dd679-6e3f-4b4d-b255-87ccc326aea7